openapi: 3.0.1
info:
  title: QM-IceCream-API
  version: "0.0.1"
  description: |
    ice cream api

paths:
  /icecreams:
    get:
      tags:
        - icecream
      operationId: iceCreamList
      summary: the list of all ice cream varieties
      responses:
        200:
          description: the list of all ice cream varieties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schema/iceCream.yaml'
    post:
      tags:
        - icecream
      operationId: storeIceCream
      summary: store ice cream object
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schema/iceCream.yaml'
      responses:
        200:
          description: ice cream data stored
    delete:
      tags:
        - icecream
      operationId: deleteIceCream
      summary: delete ice cream object
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schema/iceCream.yaml'
      responses:
        200:
          description: ice cream data deleted